{
 "title": "Vast Dashboard",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "CPU_Max_Power", "label": "CPU Max Power", "query": "300" },
   { "name": "BasePower", "label": "BasePower", "query": "100" }
  ]
 },
 "panels": [
  {
   "title": "Account Balance",
   "type": "stat",
   "description": "Reported by vast api. ",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vastai_account_balance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pending Payout",
   "type": "stat",
   "description": "Reported by vast api. ",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vastai_current_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Machines verfied",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vast_machine_Verification)/ sum(vast_machine_hostname) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Machines",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(vast_machine_hostname)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Used Bid",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vastai_machine_gpu_rented_bid_demand) / sum(vast_machine_gpu_name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Used On-demand",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vastai_machine_gpu_rented_on_demand) / sum(vast_machine_gpu_name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actual vs Vast registred",
   "type": "gauge",
   "description": "This shows how many of the GPUs are detected by the systems vs what each machine has registered on vast. ",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gpu:utilization:percent{})/sum(vast_machine_gpu_name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Machine earnings per day",
   "type": "timeseries",
   "description": "Reported by vast api. ",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(vastai_machine_earn_hour) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Reported Income per day",
   "type": "stat",
   "description": "Reported by vast for all machines",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(vastai_machine_earn_hour)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Income per hour",
   "type": "stat",
   "description": "Based on incress of the pending balance over the laste hour",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deriv(vastai_current_total[1h]) * 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machines Listed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vast_machine_Listed)/ sum(vast_machine_hostname) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Toal GPU's",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(vast_machine_gpu_name)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Used Reserved",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vastai_machine_gpu_rented_on_reserved) / sum(vast_machine_gpu_name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU's Idle",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vastai_machine_gpu_idle) / sum(vast_machine_gpu_name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine usage On-demand",
   "type": "timeseries",
   "description": "Avraged over 24h as reported by vast api. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n  (\r\n    sum(vastai_machine_gpu_rented_on_demand) by (hostname) / \r\n    sum(vast_machine_gpu_name) by (hostname)\r\n  )[10m:15s]\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Power",
   "type": "gauge",
   "description": "Total amount of power used by systems",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  sum by (job) (\r\n    $BasePower + $CPU_Max_Power *  \r\n    irate(node_cpu_seconds_total{mode=\"system\"}[$__rate_interval])\r\n  ) /   sum by (job) (\r\n    (irate(node_cpu_seconds_total{}[$__rate_interval]))\r\n  ) \r\n)   + sum(\r\n  sum by (job) (gpu:power_usage:watts)\r\n) \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machines Power usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (job) (irate(node_cpu_seconds_total{mode=\"system\"}[$__rate_interval])) / on(job) group_left sum by (job)((irate(node_cpu_seconds_total{}[$__rate_interval]))) * $CPU_Max_Power * count by (job)(node_cpu_temperature{package=~\"[0-9]+\"}) + sum by (job) (gpu:power_usage:watts) + $BasePower",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine_Info",
   "type": "table",
   "description": "As reported by vast api.",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 25 },
   "targets": [
    { "expr": "vast_machine_gpu_name", "legendFormat": "__auto" },
    { "expr": "vast_machine_hostname", "legendFormat": "__auto" },
    {
     "expr": "vastai_machine_current_rentals_resident",
     "legendFormat": "__auto"
    },
    { "expr": "vastai_machine_gpu_idle", "legendFormat": "__auto" },
    {
     "expr": "vastai_machine_gpu_rented_bid_demand",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_rented_on_reserved",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_rented_on_demand",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_avail_disk_space",
     "legendFormat": "__auto"
    },
    { "expr": "vast_machine_Listed", "legendFormat": "__auto" },
    { "expr": "vast_machine_Verification", "legendFormat": "__auto" },
    { "expr": "APT_UPGRADABLE_PACKAGES", "legendFormat": "__auto" },
    { "expr": "vastai_machine_end_date", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reported GPU Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 13, "y": 25 },
   "targets": [
    {
     "expr": "count(gpu:memory_used:bytes / 1024 / 1024) by (Hostname)",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:sm_clock:mhz{Hostname=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Updates",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 25 },
   "targets": [
    { "expr": "APT_UPGRADABLE_PACKAGES", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Machine Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance) (irate(node_cpu_seconds_total[$__rate_interval]))) * 100\r\n",
     "legendFormat": "__auto"
    },
    { "expr": "node_uname_info", "legendFormat": "__auto" },
    {
     "expr": "(sum by(instance) (node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - node_memory_Buffers_bytes{} - node_memory_Cached_bytes{})) / sum by(instance) (node_memory_MemTotal_bytes{}) * 100\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_time_seconds - on(instance) node_boot_time_seconds ) / 60 /60",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(max by(instance)(rate(node_network_transmit_bytes_total[1m])*8/1000000), 0.1)\r\n\r\n\r\n\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(max by(instance)(rate(node_network_receive_bytes_total[1m])*8/1000000), 0.1)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - avg by(instance)(node_filesystem_avail_bytes{mountpoint=\"/\"}/node_filesystem_size_bytes{mountpoint=\"/\"})) * 100\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - avg by(instance)(node_filesystem_avail_bytes{mountpoint=\"/var/lib/docker\"}/node_filesystem_size_bytes{mountpoint=\"/var/lib/docker\"})) * 100\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(instance)(node_cpu_temperature{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU Occupancy",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"4\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vastai_machine_gpu_occupancy{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine Reliability",
   "type": "timeseries",
   "description": "As reported by vast api.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(vast_machine_Reliability) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Machine Online Status",
   "type": "state-timeline",
   "description": "As reported by vast api.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by(hostname) (vast_machine_timeout)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Machine GPU Error State",
   "type": "table",
   "description": "Current error state for GPU (2 for error, 1 for no error, 0 unknown state)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gpu:error_state:status{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:error_state:status{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:error_state:status{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:error_state:status{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:error_state:status{gpu=\"4\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:error_state:status{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:error_state:status{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:error_state:status{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine Reporting Error",
   "type": "state-timeline",
   "description": "As reported by vast api.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by(hostname) (vastai_machine_ErrorDescription)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Machine GPU VRAM Temps ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu:memory_temp:celsius{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:memory_temp:celsius{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:memory_temp:celsius{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:memory_temp:celsius{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:memory_temp:celsius{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:memory_temp:celsius{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:memory_temp:celsius{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:memory_temp:celsius{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU Core Hot Spot",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "last_over_time(gpu:hotspot_temp:celsius{gpu=\"0\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(gpu:hotspot_temp:celsius{gpu=\"1\"}[1m])\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(gpu:hotspot_temp:celsius{gpu=\"2\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(gpu:hotspot_temp:celsius{gpu=\"3\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(gpu:hotspot_temp:celsius{gpu=\"4\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(gpu:hotspot_temp:celsius{gpu=\"5\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(gpu:hotspot_temp:celsius{gpu=\"6\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(gpu:hotspot_temp:celsius{gpu=\"7\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU FAN Speeds",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "gpu:fan_speed:percent{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:fan_speed:percent{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:fan_speed:percent{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:fan_speed:percent{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:fan_speed:percent{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:fan_speed:percent{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:fan_speed:percent{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:fan_speed:percent{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU Temps",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu:core_temp:celsius{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:core_temp:celsius{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:core_temp:celsius{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:core_temp:celsius{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:core_temp:celsius{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:core_temp:celsius{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:core_temp:celsius{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:core_temp:celsius{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU Thermal Throttle",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "gpu:throttle_reason:bool{reason=\"SwThermalSlowdown\", gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:throttle_reason:bool{reason=\"SwThermalSlowdown\", gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:throttle_reason:bool{reason=\"SwThermalSlowdown\", gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:throttle_reason:bool{reason=\"SwThermalSlowdown\", gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:throttle_reason:bool{reason=\"SwThermalSlowdown\", gpu=\"4\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:throttle_reason:bool{reason=\"SwThermalSlowdown\", gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:throttle_reason:bool{reason=\"SwThermalSlowdown\", gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:throttle_reason:bool{reason=\"SwThermalSlowdown\", gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU Power",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "gpu:power_usage:watts{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:power_usage:watts{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:power_usage:watts{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:power_usage:watts{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:power_usage:watts{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:power_usage:watts{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:power_usage:watts{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:power_usage:watts{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU AER Errors",
   "type": "table",
   "description": "Cont of AER in system logs per GPU:  Advanced Error Reporting by PCI Express devices",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gpu:aer_errors:total{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:aer_errors:total{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:aer_errors:total{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:aer_errors:total{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:aer_errors:total{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:aer_errors:total{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:aer_errors:total{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:aer_errors:totalE{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Historic Machine earnings for GPUs  per day",
   "type": "timeseries",
   "description": "As reported by vast api for the day before. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(vastai_per_machine_gpu_earn)  by (machine_id) ) !=0",
     "legendFormat": "{{machine_id}}"
    }
   ]
  },
  {
   "title": "Historic Machine earnings per day",
   "type": "timeseries",
   "description": "As reported by vast api for the day before. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(vastai_per_machine_gpu_earn+vastai_per_machine_bwd_earn+vastai_per_machine_bwu_earn+vastai_per_machine_sto_earn)  by (machine_id) ) !=0",
     "legendFormat": "{{machine_id}}"
    }
   ]
  },
  {
   "title": "Machine avail disk space reported by vast",
   "type": "timeseries",
   "description": "As reported by vast api.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(sum(vastai_machine_avail_disk_space)  by (machine_id) ) !=0",
     "legendFormat": "{{machine_id}}"
    }
   ]
  },
  {
   "title": "Historic Machine earnings storage  per day",
   "type": "timeseries",
   "description": "As reported by vast api for the day before. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(vastai_per_machine_sto_earn)  by (machine_id) ) !=0",
     "legendFormat": "{{machine_id}}"
    }
   ]
  },
  {
   "title": "Historic Machine earnings Bandwith  per day",
   "type": "timeseries",
   "description": "As reported by vast api for the day before. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(vastai_per_machine_bwd_earn+vastai_per_machine_bwu_earn)  by (machine_id) ) !=0",
     "legendFormat": "{{machine_id}}"
    }
   ]
  },
  {
   "title": "Machine Internet Upload speed",
   "type": "timeseries",
   "description": "Reported by vast api. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum(vastai_machine_InetUp)  by (machine_id)",
     "legendFormat": "{{machine_id}}"
    }
   ]
  },
  {
   "title": "Machine Internet Down speed",
   "type": "timeseries",
   "description": "Reported by vast api. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum(vast_machine_InetDown)  by (machine_id)",
     "legendFormat": "{{machine_id}}"
    }
   ]
  }
 ]
}