{
 "title": "DC Overview",
 "tags": [
  "Prometheus",
  "NVIDIA",
  "Linux"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Machine GPU Error State",
   "type": "table",
   "description": "Current error state for GPU (2 for error, 1 for no error, 0 unknown state)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "GPU_ERROR_STATE{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{gpu=\"4\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_ERROR_STATE{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU VRAM Temps ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_VRAM_TEMP{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU Temps",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU Power",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU Core Hot Spot",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_HOT_SPOT_TEMP{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU FAN Speeds",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU AER Errors",
   "type": "table",
   "description": "Cont of AER in system logs per GPU:  Advanced Error Reporting by PCI Express devices",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORS{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "GPU_AER_TOTAL_ERRORSE{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU Thermal Throttle",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"4\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_CLOCKS_THROTTLE_REASON{reason=\"SwThermalSlowdown\", gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reported GPU Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_FB_USED) by (Hostname)",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{Hostname=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Updates",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 29 },
   "targets": [
    { "expr": "APT_UPGRADABLE_PACKAGES", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Machine Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance) (irate(node_cpu_seconds_total[$__rate_interval]))) * 100\r\n",
     "legendFormat": "__auto"
    },
    { "expr": "node_uname_info", "legendFormat": "__auto" },
    {
     "expr": "(sum by(instance) (node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - node_memory_Buffers_bytes{} - node_memory_Cached_bytes{})) / sum by(instance) (node_memory_MemTotal_bytes{}) * 100\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_time_seconds - on(instance) node_boot_time_seconds ) / 60 /60",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(max by(instance)(rate(node_network_transmit_bytes_total[1m])*8/1000000), 0.1)\r\n\r\n\r\n\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(max by(instance)(rate(node_network_receive_bytes_total[1m])*8/1000000), 0.1)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - avg by(instance)(node_filesystem_avail_bytes{mountpoint=\"/\"}/node_filesystem_size_bytes{mountpoint=\"/\"})) * 100\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - avg by(instance)(node_filesystem_avail_bytes{mountpoint=\"/var/lib/docker\"}/node_filesystem_size_bytes{mountpoint=\"/var/lib/docker\"})) * 100\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(instance)(node_cpu_temperature{})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}