{
 "title": "DC OverView",
 "tags": [
  "Prometheuse",
  "Nvidia",
  "Linux"
 ],
 "time": { "from": "now-10s", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Machine GPU Core Hot Spot",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu:hotspot_temp:celsius{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:hotspot_temp:celsius{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:hotspot_temp:celsius{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:hotspot_temp:celsius{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:hotspot_temp:celsius{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:hotspot_temp:celsius{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:hotspot_temp:celsius{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:hotspot_temp:celsius{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU FAN Speeds",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "gpu:fan_speed:percent{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:fan_speed:percent{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:fan_speed:percent{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:fan_speed:percent{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:fan_speed:percent{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:fan_speed:percent{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:fan_speed:percent{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:fan_speed:percent{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU Power",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "gpu:power_usage:watts{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:power_usage:watts{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:power_usage:watts{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:power_usage:watts{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:power_usage:watts{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:power_usage:watts{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:power_usage:watts{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:power_usage:watts{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU Temps",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu:core_temp:celsius{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:core_temp:celsius{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:core_temp:celsius{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:core_temp:celsius{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:core_temp:celsius{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:core_temp:celsius{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:core_temp:celsius{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:core_temp:celsius{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU VRAM Temps ",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu:memory_temp:celsius{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:memory_temp:celsius{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:memory_temp:celsius{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:memory_temp:celsius{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:memory_temp:celsius{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:memory_temp:celsius{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:memory_temp:celsius{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:memory_temp:celsius{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU Thermal Throttle",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "gpu:throttle_reason:bool{reason=\"SwThermalSlowdown\", gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:throttle_reason:bool{reason=\"SwThermalSlowdown\", gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:throttle_reason:bool{reason=\"SwThermalSlowdown\", gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:throttle_reason:bool{reason=\"SwThermalSlowdown\", gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:throttle_reason:bool{reason=\"SwThermalSlowdown\", gpu=\"4\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:throttle_reason:bool{reason=\"SwThermalSlowdown\", gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:throttle_reason:bool{reason=\"SwThermalSlowdown\", gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:throttle_reason:bool{reason=\"SwThermalSlowdown\", gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine GPU AER_ ERRORS",
   "type": "table",
   "description": "Cont of AER in system logs per GPU:  Advanced Error Reporting by PCI Express devices",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gpu:aer_errors:total{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:aer_errors:total{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:aer_errors:total{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:aer_errors:total{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:aer_errors:total{gpu=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:aer_errors:total{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:aer_errors:total{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:aer_errors:total{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Updates",
   "type": "table",
   "description": "APT_UPGRADABLE_PACKAGES Updated once every 1h\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    { "expr": "APT_UPGRADABLE_PACKAGES" }
   ]
  },
  {
   "title": "Machine GPU Error State",
   "type": "table",
   "description": "Current error state for GPU (2 for error, 1 for no error, 0 unknown state)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gpu:error_state:status{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:error_state:status{gpu=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:error_state:status{gpu=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:error_state:status{gpu=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:error_state:status{gpu=\"4\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:error_state:status{gpu=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:error_state:status{gpu=\"6\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu:error_state:status{gpu=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Driver and count",
   "type": "table",
   "description": "GPU drivers\n",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "count(gpu:memory_used:bytes / 1024 / 1024) by (Hostname)"
    },
    {
     "expr": "gpu:sm_clock:mhz{Hostname=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine Overview",
   "type": "table",
   "gridPos": { "h": 33, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance) (irate(node_cpu_seconds_total[$__rate_interval]))) * 100\r\n",
     "legendFormat": "__auto"
    },
    { "expr": "node_uname_info", "legendFormat": "__auto" },
    {
     "expr": "(sum by(instance) (node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - node_memory_Buffers_bytes{} - node_memory_Cached_bytes{})) / sum by(instance) (node_memory_MemTotal_bytes{}) * 100\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_time_seconds - on(instance) node_boot_time_seconds ) / 60 /60",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(max by(instance)(rate(node_network_transmit_bytes_total[1m])*8/1000000), 0.1)\r\n\r\n\r\n\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(max by(instance)(rate(node_network_receive_bytes_total[1m])*8/1000000), 0.1)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - avg by(instance)(node_filesystem_avail_bytes{mountpoint=\"/\"}/node_filesystem_size_bytes{mountpoint=\"/\"})) * 100\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - avg by(instance)(node_filesystem_avail_bytes{mountpoint=\"/var/lib/docker\"}/node_filesystem_size_bytes{mountpoint=\"/var/lib/docker\"})) * 100 \r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(instance)(node_cpu_temperature{})\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - avg by(instance)(node_filesystem_avail_bytes{mountpoint=\"/var/lib/mfs\"}/node_filesystem_size_bytes{mountpoint=\"/var/lib/mfs\"})) * 100"
    },
    {
     "expr": "(1 - avg by(instance)(node_filesystem_avail_bytes{mountpoint=~\"/mnt/mfschunks1|/mnt/chunks4\"}/node_filesystem_size_bytes{mountpoint=~\"/mnt/mfschunks1|/mnt/chunks4\"})) * 100"
    }
   ]
  }
 ]
}